2022-09-19 15:47:01,258 INFO    MainThread:18596 [wandb_setup.py:_flush():71] setting env: {'run_name': 'KPM_HLT_2022', 'api_key': '***REDACTED***', 'silent': 'true'}
2022-09-19 15:47:01,258 INFO    MainThread:18596 [wandb_setup.py:_flush():71] setting login settings: {}
2022-09-19 15:47:01,259 INFO    MainThread:18596 [wandb_init.py:_log_setup():371] Logging user logs to c:\Users\super\Desktop\HLT_Project\KeyPointMatching\wandb\run-20220919_154701-11scwp1a\logs\debug.log
2022-09-19 15:47:01,259 INFO    MainThread:18596 [wandb_init.py:_log_setup():372] Logging internal logs to c:\Users\super\Desktop\HLT_Project\KeyPointMatching\wandb\run-20220919_154701-11scwp1a\logs\debug-internal.log
2022-09-19 15:47:01,259 INFO    MainThread:18596 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001FEBC23C0A0>
2022-09-19 15:47:01,259 INFO    MainThread:18596 [wandb_init.py:init():404] calling init triggers
2022-09-19 15:47:01,260 INFO    MainThread:18596 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-09-19 15:47:01,260 INFO    MainThread:18596 [wandb_init.py:init():449] starting backend
2022-09-19 15:47:01,260 INFO    MainThread:18596 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2022-09-19 15:47:01,264 INFO    MainThread:18596 [backend.py:ensure_launched():199] starting backend process...
2022-09-19 15:47:01,502 INFO    MainThread:18596 [backend.py:ensure_launched():204] started backend process with pid: 3740
2022-09-19 15:47:01,503 INFO    MainThread:18596 [wandb_init.py:init():458] backend started and connected
2022-09-19 15:47:01,505 INFO    MainThread:18596 [wandb_run.py:_label_probe_notebook():917] probe notebook
2022-09-19 15:47:01,506 INFO    MainThread:18596 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-09-19 15:47:01,507 INFO    MainThread:18596 [wandb_init.py:init():519] updated telemetry
2022-09-19 15:47:01,908 INFO    MainThread:18596 [wandb_init.py:init():549] communicating current version
2022-09-19 15:47:04,861 INFO    MainThread:18596 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.13.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-09-19 15:47:04,861 INFO    MainThread:18596 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-09-19 15:47:34,865 INFO    MainThread:18596 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2022-09-19 15:47:34,865 ERROR   MainThread:18596 [wandb_init.py:init():569] backend process timed out
2022-09-19 15:47:34,865 ERROR   MainThread:18596 [wandb_init.py:init():578] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-09-19 15:47:34,889 ERROR   MainThread:18596 [wandb_init.py:init():944] error
Traceback (most recent call last):
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\wandb_init.py", line 582, in init
    backend.cleanup()
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\backend\backend.py", line 228, in cleanup
    self.interface.join()
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface_queue.py", line 481, in join
    super(InterfaceQueue, self).join()
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface.py", line 591, in join
    self._communicate_shutdown()
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface_queue.py", line 478, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface_queue.py", line 237, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
